name: Update Design from Figma

on:
  workflow_dispatch: # Запуск вручную
  schedule:
    - cron: '0 0 * * *' # Ежедневный запуск в полночь (UTC)

jobs:
  update-design:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install axios

      # Шаг 4: Экспорт ресурсов из Figma
      - name: Export resources from Figma
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
        run: |
          # Используем Node.js для запроса к API Figma
          const axios = require('axios');
          const fs = require('fs');

          const FIGMA_TOKEN = process.env.FIGMA_TOKEN;
          const FIGMA_FILE_ID = process.env.FIGMA_FILE_ID;

          const exportResources = async () => {
            try {
              // Запрос к API Figma для получения структуры файла
              const response = await axios.get(`https://api.figma.com/v1/files/${FIGMA_FILE_ID}`, {
                headers: { 'X-Figma-Token': FIGMA_TOKEN },
              });

              const nodes = response.data.document.children;

              // Пример: Сохранение CSS или изображений
              fs.writeFileSync('styles.css', '/* Generated by Figma */\n');
              console.log('CSS file created.');

              // Здесь можно добавить логику для экспорта изображений или других ресурсов
            } catch (error) {
              console.error('Error exporting resources:', error);
            }
          };

          exportResources();
      
      # Шаг 5: Коммит изменений
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update from Figma" || echo "No changes to commit"
          git push
